site_name: libigl
site_url: 'http://gabuzome.github.io/libigl/'
repo_name: 'libigl/libigl'
repo_url: 'https://github.com/gabuzome/gabuzome.github.io'
site_description: "Simple C++ geometry processing library"
strict: true
docs_dir: 'docs'
remote_branch: 'master'
theme:
  name: material
  favicon: 'favicon.ico'
  logo:
    icon: ' '
  palette:
    primary: 'light blue'
    accent: 'blue'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/libigl'
markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - toc:
      permalink: true
  - scripts.figureAltCaption
  - markdown.extensions.smarty
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - scripts.fixPaths:
      variables:
        repo_url: 'https://github.com/libigl/libigl/tree/master'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'css/style.css'
pages:
  - Home: libigl/index.md
  - Tutorial: libigl/tutorial.md
    # - "Chapter 1: Introduction to libigl": tutorial/chapter-1.md
    # - "Chapter 2: Discrete Geometric Quantities and Operators": tutorial/chapter-2.md
    # - "Chapter 3: Matrices and Linear Algebra": tutorial/chapter-3.md
    # - "Chapter 4: Shape Deformation": tutorial/chapter-4.md
    # - "Chapter 5: Parametrization": tutorial/chapter-5.md
    # - "Chapter 6: External libraries": tutorial/chapter-6.md
    # - "Chapter 7: Miscellaneous": tutorial/chapter-7.md
    # - "Chapter 8: Outlook for continuing development": tutorial/chapter-8.md
  - Compilation:
    - Example Project: libigl/example-project.md
    - Static Library: libigl/static-library.md
    - External Dependencies: libigl/third-party.md
    - Python Bindings: libigl/python-bindings.md
  - Contributing:
    - Style Guidelines: libigl/style-guidelines.md
    - Bug Report: libigl/CONTRIBUTING.md
    - Creating a Pull Request: libigl/before-submitting-pull-request.md
    - Unit Tests: libigl/unit-tests.md
  - Misc:
    - Matlab-libigl Cheatsheet: libigl/matlab-to-eigen.md
    - Coding Tips: libigl/coding-guidelines.md
    - File Formats:
      - Index: libigl/file-formats/index.md
      - bf: libigl/file-formats/bf.md
      - dmat: libigl/file-formats/dmat.md
      - rbr: libigl/file-formats/rbr.md
      - tgf: libigl/file-formats/tgf.md
      - xml: libigl/file-formats/xml.md
    - Building the Website: libigl/readme.md
  - FAQ: libigl/faq.md
  - About:
    - Release History: libigl/RELEASE_HISTORY.md
    - License: libigl/LICENSE.md
